# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1', models.FileField(upload_to='samples')),
                ('sample2', models.FileField(upload_to='samples')),
                ('sample3', models.FileField(upload_to='samples')),
                ('sample4', models.FileField(upload_to='samples')),
                ('sample5', models.FileField(upload_to='samples')),
            ],
        ),
    ]
